name: MyFirstCustomAction

on: [push]

jobs:
  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Print Date Job 1
        run: echo "The date is $(date)"

  job2:
    name: Second Job
    runs-on: windows-latest
    steps:
      - name: Print Date Job 2
        run: echo "The date is $(Get-Date)"
        shell: powershell

  job3:
    name: Third Job
    runs-on: macos-latest
    steps:
      - name: Print Date Job 3
        run: echo "The date is $(date)"

  job4:
    name: Fourth Job
    needs: [job1, job2, job3]
    runs-on: windows-latest
    steps:
      - name: Print Date Job 2
        run: echo "The date is $(Get-Date)"
        shell: powershell
